"""create interview and interview type tables

Revision ID: 341443bcf14e
Revises: 8e5e1b94a7eb
Create Date: 2025-06-07 10:18:08.809848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341443bcf14e'
down_revision: Union[str, None] = '8e5e1b94a7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_type')
    )
    op.create_index(op.f('ix_interview_types_id'), 'interview_types', ['id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('interview_date', sa.DateTime(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_interview_types_id'), table_name='interview_types')
    op.drop_table('interview_types')
    # ### end Alembic commands ###
