"""create interview type table

Revision ID: 54d61e12cacb
Revises: 8e5e1b94a7eb
Create Date: 2025-06-07 11:13:09.224927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d61e12cacb'
down_revision: Union[str, None] = '8e5e1b94a7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_type')
    )
    op.create_index(op.f('ix_interview_types_id'), 'interview_types', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_types_id'), table_name='interview_types')
    op.drop_table('interview_types')
    # ### end Alembic commands ###
