"""application stage unique name

Revision ID: 8e5e1b94a7eb
Revises: bdf9b42b6397
Create Date: 2025-05-30 21:26:11.297685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5e1b94a7eb'
down_revision: Union[str, None] = 'bdf9b42b6397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_applications_stage_application_stage', table_name='applications_stage')
    op.create_index(op.f('ix_applications_stage_application_stage'), 'applications_stage', ['application_stage'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_stage_application_stage'), table_name='applications_stage')
    op.create_index('ix_applications_stage_application_stage', 'applications_stage', ['application_stage'], unique=False)
    # ### end Alembic commands ###
